# Footstep parameterization for the Aldebaran Robotics Nao humanoid

### footstep settings ##########################################################
# Footstep displacement vectors (in meter / rad)
# WARNING: data type has to be float since integers will cause an exception
footsteps/x:     [0.0,0.04,0.04,0.04,0.04,0.0,0.00,0.00,-0.04,-0.04,-0.04,-0.04, 0.00, 0.04]
footsteps/y:     [0.0,0.00,0.00,0.04,0.04,0.0,0.04,0.04, 0.00, 0.00, 0.04, 0.04,-0.01,-0.01]
footsteps/theta: [0.0,0.00,0.30,0.00,0.30,0.3,0.00,0.30, 0.00, 0.30, 0.00, 0.30, 0.00, 0.00]

### footstep settings ##########################################################
foot/size/x: 0.15
foot/size/y: 0.08
foot/size/z: 0.015
foot/separation: 0.095
foot/origin_shift/x: 0.02
foot/origin_shift/y: 0.0
foot/max/step/x: 0.04
foot/max/step/y: 0.04
foot/max/step/theta: 0.349
foot/max/inverse/step/x: 0.04
foot/max/inverse/step/y: 0.01
foot/max/inverse/step/theta: 0.05